using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Thuddle.Api.Migrations
{
    /// <inheritdoc />
    public partial class RemovePrimaryAuctionItemBgg : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                INSERT INTO "AuctionItemBoardGames" ("Id", "ItemId", "BggId", "SortOrder", "AddedAt")
                SELECT gen_random_uuid(), ai."Id", ai."BggId", 0, NOW() AT TIME ZONE 'UTC'
                FROM "AuctionItems" ai
                WHERE ai."BggId" IS NOT NULL
                AND NOT EXISTS (
                    SELECT 1 FROM "AuctionItemBoardGames" abg
                    WHERE abg."ItemId" = ai."Id" AND abg."BggId" = ai."BggId"
                );
            """);

            migrationBuilder.DropForeignKey(
                name: "FK_AuctionItems_BoardGames_BggId",
                table: "AuctionItems");

            migrationBuilder.DropIndex(
                name: "IX_AuctionItems_BggId",
                table: "AuctionItems");

            migrationBuilder.DropColumn(
                name: "BggId",
                table: "AuctionItems");

            migrationBuilder.DropColumn(
                name: "BggImageUrl",
                table: "AuctionItems");

            migrationBuilder.AddColumn<bool>(
                name: "DescriptionAutoGenerated",
                table: "AuctionItems",
                type: "boolean",
                nullable: false,
                defaultValue: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "DescriptionAutoGenerated",
                table: "AuctionItems");

            migrationBuilder.AddColumn<int>(
                name: "BggId",
                table: "AuctionItems",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "BggImageUrl",
                table: "AuctionItems",
                type: "text",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_AuctionItems_BggId",
                table: "AuctionItems",
                column: "BggId");

            migrationBuilder.AddForeignKey(
                name: "FK_AuctionItems_BoardGames_BggId",
                table: "AuctionItems",
                column: "BggId",
                principalTable: "BoardGames",
                principalColumn: "BggId",
                onDelete: ReferentialAction.SetNull);
        }
    }
}
